version: '3.9'

networks:
  default:
    name: konigle
    driver: bridge

services:
  backend:
    build:
        context: ../
        dockerfile: docker/Dockerfile
    container_name: konigle
    platform: linux/amd64
    command: python manage.py runserver 0.0.0.0:8007
    volumes:
      - "../app:/konigle/app"
    ports:
      - "8007:8007"
    env_file:
      - ../.env