# Generated by Django 4.1.3 on 2022-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsubscription",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="emailsubscription",
            unique_together={("email", "store")},
        ),
    ]
